project:
  type: book
  output-dir: docs
  
book:
  title: "R as GIS for Economists"
  author: "Taro Mieno"
  site-url: https://tmieno2.github.io/R-as-GIS-for-Economists/
  repo-url: https://github.com/tmieno2/R-as-GIS-for-Economists
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - text: "---"
    - part: "Demonstrations"
      chapters:
        - chapters/01-Demonstration.qmd
    - text: "---"
    - part: "Foundations"
      chapters:
        - chapters/02-VectorDataBasics.qmd
        - chapters/03-SpatialInteractionVectorVector.qmd
        - chapters/04-RasterDataBasics.qmd
        - chapters/05-SpatialInteractionVectorRaster.qmd
    - text: "---"
    - part: "Extensions"
      chapters:
        - chapters/06-stars.qmd
        - chapters/07-CreateMaps-ggplot.qmd
        - chapters/08-DownloadSpatialData.qmd
    - text: "---"
    - part: "(slightly) Advanced Topics"
      chapters:
        - chapters/09-SpeedThingsUp.qmd
    - text: "---"
  appendices:
    - chapters/A1-ParallelComputing.qmd
    - chapters/A2-ggplot2-appendix.qmd

bibliography: RGIS.bib
reference-location: margin
footnotes-hover: true

format:
  html: 
    include-in-header:
      - analytics.html
    css: style.css
    toc: true
    toc-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 520px
      gutter-width: 1rem
    number-sections: true
    number-depth: 4
    code-link: true
    callout-icon: false
    fig-align: center
    # fig-cap-location: top
    code-tools: true

execute:
  warning: false
  cache: true
  cache-lazy: false
  message: false
  fig-align: center

theme: 
  light: cosmo